export const BEGIN_GATEWAY_ZERO_TRANSFER = 'BEGIN_GATEWAY_ZERO_TRANSFER';
export const CRYPTO_UNIFORM_NET_ENABLE = 'CRYPTO_UNIFORM_NET_ENABLE';
export const ZERO_ENCRYPT_WAIT_HASH = 'ZERO_ENCRYPT_WAIT_HASH';
export const MAX_MESSAGE_SIZE = 1024 * 1024;
